model:
  network:
    _target_: lib.model.network.ImplicitNetwork
    d_in: 3
    d_out: 1
    width: 256
    depth: 4
    geometric_init: true
    bias: 1
    skip_in: 4
    weight_norm: true
    multires: 4
    pose_cond_dim: 69
    pose_cond_layer: []
    pose_embed_dim: -1
    shape_cond_dim: 10
    shape_cond_layer: []
    shape_embed_dim: -1
    latent_cond_dim: 64
    latent_cond_layer: [0]
    latent_embed_dim: -1

